<?php include('db_connect.php');

if(in_array("18",$_SESSION['login_Permisions']))
{
	?>
	<div class="container-fluid professional-view-page view-requisitions">
		<div class="row view-summary-grid">
			<div class="col-md-4"><div class="view-summary-card is-inactive"><span class="view-summary-icon"><i class="fa fa-clock"></i></span><div class="view-summary-copy"><h6>Pending</h6><h3><?php echo $conn->query("SELECT COUNT(*) AS c FROM paper_requisition WHERE del_status=0 AND req_status=0")->fetch_assoc()['c']; ?></h3></div></div></div>
			<div class="col-md-4"><div class="view-summary-card"><span class="view-summary-icon"><i class="fa fa-adjust"></i></span><div class="view-summary-copy"><h6>Partially Received</h6><h3><?php echo $conn->query("SELECT COUNT(*) AS c FROM paper_requisition WHERE del_status=0 AND req_status=1")->fetch_assoc()['c']; ?></h3></div></div></div>
			<div class="col-md-4"><div class="view-summary-card is-active"><span class="view-summary-icon"><i class="fa fa-check-circle"></i></span><div class="view-summary-copy"><h6>Received</h6><h3><?php echo $conn->query("SELECT COUNT(*) AS c FROM paper_requisition WHERE del_status=0 AND req_status NOT IN (0,1)")->fetch_assoc()['c']; ?></h3></div></div></div>
		</div>

		<div class="col-lg-12">
			<div class="row">
				<div class="col-md-12">
					<div class="card professional-view-card">

						<div class="row" style="background-color:#f9f9f9">
							<div class="col-lg-6">
								<div class="view-heading"><span class="view-heading-icon"><i class="fa fa-clipboard"></i></span><div><h2>Requisitions</h2><p>Review requests, assignment, and fulfillment status.</p></div></div>
							</div>
							<div class="col-lg-6">
								<a class="btn btn-primary btn-sm float-right m-3" href="index.php?page=Requisition/add-requisition" id="new_order">
									<i class="fa fa-plus"></i> Add Requisition
								</a>
							</div>
						</div>
						<hr>

						<div class="card-body table-responsive">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Req No</th>
										<th>Supplier</th>
										<th>Required Date</th>									
										<th>Generated by</th>
										<th>Status</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									<?php
									$category = $conn->query("SELECT a.*,b.supp_name,c.name as userName FROM paper_requisition as a LEFT JOIN suppliers as b on a.supp_id = b.supp_id INNER JOIN users as c on a.user_id = c.id WHERE del_status = 0 order by a.id DESC");
									while($row=$category->fetch_assoc()):
										$supp_class = 'color:black';
										$supplier_name = $row['supp_name'];
										if($row['supp_name'] == ""){
											$supplier_name = "UnAssigned";
											$supp_class = 'color:red';
										}
										?>
										<tr>
											<td class="text-center">REQ-<?php echo $row['id'] ?></td>
											<td style="<?= $supp_class ?>"><?php echo $supplier_name ?></td>
											<td><?php echo $row['required_date'] ?></td>
											<td><?php echo $row['userName'] ?></td>
											<td><?php
											if($row['req_status'] == 0){
												?><span style="color:red"><b>Pending</b></span><?php
											}elseif($row['req_status'] == 1){
												?><span style="color:blue"><b>Partial Received</b></span><?php
											}else{
												?>
												<span style="color: green"><b>Received</b></span>
												<?php
											}
											?></td>
											<td>
												<div class="requisition-actions">
													<a class="requisition-action-btn view" href="index.php?page=Requisition/view-requisition-details&id=<?php echo (int)$row['id'] ?>" title="View requisition" aria-label="View requisition"><i class="fa fa-eye"></i><span>View</span></a>
												<?php 
												if($row['supp_name'] == ""){
													?>
													<button type="button" class="requisition-action-btn assign supplier_tagged" data-value="<?php echo (int)$row['id'] ?>" data-code="REQ-<?php echo (int)$row['id'] ?>" data-toggle="modal" data-target="#status_modal" title="Assign supplier" aria-label="Assign supplier"><i class="fa fa-link"></i><span>Assign</span></button>
													<?php
												}
												?>
												</div>
											</td>

										</tr>

									<?php endwhile; ?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- Table Panel -->
			</div>
		</div>	


		<style>
			.requisition-actions{display:flex;align-items:center;justify-content:center;gap:6px;white-space:nowrap}.requisition-action-btn{display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;padding:0;border:1px solid #e0e1e4;border-radius:8px;font-size:12px;line-height:1;color:#55565b;background:#fff;transition:.15s;cursor:pointer}.requisition-action-btn span{display:none}.requisition-action-btn:hover{text-decoration:none;transform:translateY(-1px)}.requisition-action-btn.view{color:#267b53;border-color:#cce7d9;background:#eff9f4}.requisition-action-btn.view:hover{color:#1f6846;border-color:#8dccac;background:#e7f6ee}.requisition-action-btn.assign{color:#dc5b17;border-color:#ffd0b6;background:#fff4ed}.requisition-action-btn.assign:hover{color:#bf4910;border-color:#f36b21;background:#ffede2}
			#status_modal .modal-dialog{max-width:500px;margin:8vh auto}#status_modal .modal-content{overflow:hidden;border:0;border-radius:15px;box-shadow:0 24px 70px rgba(28,29,32,.24)}#status_modal .modal-header{display:flex!important;align-items:center;justify-content:space-between;min-height:68px;padding:15px 18px;border:0;border-bottom:1px solid #ececef;border-left:4px solid #f36b21;background:#fff!important}
			.assign-modal-heading{display:flex;align-items:center;gap:12px}.assign-modal-icon{display:grid;place-items:center;width:40px;height:40px;border-radius:11px;color:#fff;background:linear-gradient(145deg,#f36b21,#df5812);box-shadow:0 7px 16px rgba(243,107,33,.2)}.assign-modal-heading h4{margin:0;font-size:16px;font-weight:650;color:#303033}.assign-modal-heading p{margin:3px 0 0;font-size:10px;color:#898a90}.assign-modal-close{display:grid;place-items:center;width:32px;height:32px;padding:0;border:0;border-radius:8px;font-size:14px;color:#6f7075;background:#f4f4f5;opacity:1}.assign-modal-close:hover{color:#303033;background:#eaeaec}
			#status_modal .modal-body{padding:20px;background:#f7f7f8}.assign-context{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:16px;padding:11px 13px;border:1px solid #e4e5e8;border-radius:9px;background:#fff}.assign-context span{font-size:10px;color:#85868c}.assign-context strong{font-size:11px;color:#303033}.assign-field label{display:block;margin:0 0 7px;font-size:10px;font-weight:700;letter-spacing:.05em;color:#626369;text-transform:uppercase}.assign-select-wrap{position:relative}.assign-select-wrap:before{content:'\f0c0';position:absolute;z-index:2;left:12px;top:50%;transform:translateY(-50%);font-family:'Font Awesome 5 Free','FontAwesome';font-weight:900;font-size:12px;color:#f36b21;pointer-events:none}.assign-select-wrap select{width:100%;height:44px;padding:8px 36px!important;border:1px solid #dfe1e5!important;border-radius:9px!important;font-size:11px;color:#3f4044;background:#fff;outline:0}.assign-select-wrap select:focus{border-color:#f36b21!important;box-shadow:0 0 0 3px rgba(243,107,33,.1)}.assign-help{display:block;margin-top:7px;font-size:9px;color:#929398}
			#status_modal .modal-footer{display:flex;align-items:center;justify-content:flex-end;gap:8px;padding:13px 18px;border:0;border-top:1px solid #e7e8eb;background:#fff}.assign-modal-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:38px;margin:0!important;padding:8px 14px;border-radius:9px;font-size:11px;font-weight:600}.assign-modal-btn.cancel{border:1px solid #dadce0;color:#5f6065;background:#fff}.assign-modal-btn.submit{border:1px solid #f36b21;color:#fff;background:#f36b21;box-shadow:0 7px 16px rgba(243,107,33,.18)}.assign-modal-btn.submit:hover{color:#fff;background:#df5913}
			@media(max-width:575px){#status_modal .modal-dialog{margin:12px}.requisition-action-btn{width:32px;height:32px}}
		</style>
		<div class="modal fade" id="status_modal" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<form method="post">
						<div class="modal-header">
							<div class="assign-modal-heading"><span class="assign-modal-icon"><i class="fa fa-link"></i></span><div><h4>Assign Supplier</h4><p>Connect an active supplier to this requisition.</p></div></div>
							<button type="button" class="assign-modal-close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
						</div>
						<div class="modal-body">
							<div class="assign-context"><span>Selected requisition</span><strong id="assign_requisition_code">Requisition</strong></div>
							<div class="assign-field"><label for="supplier_id"><i class="fa fa-truck"></i> Supplier</label><div class="assign-select-wrap">
							<select id="supplier_id" name="supplier_id" class="form-control" required>
								<option value="">Choose an active supplier</option>
								<?php
								$query_supp = "SELECT * FROM suppliers WHERE supp_status = 0";
								$result_supp = mysqli_query($conn,$query_supp);
								while($data_supp = mysqli_fetch_array($result_supp)){
									$selected_item = "";
									if($supplier_id == $data_supp['supp_id']){
										$selected_item = "Selected";
									}
									?>
									<option <?php echo $selected_item ?> value="<?php echo $data_supp['supp_id'] ?>"><?php echo $data_supp["supp_name"] ?></option>
									<?php
								}
								?>
							</select></div><small class="assign-help">Only active suppliers are available for assignment.</small></div>
							<input type="hidden" name="requisition_id" id="requisition_id">
						</div>
						<div class="modal-footer">
							<button type="button" class="btn assign-modal-btn cancel" data-dismiss="modal"><i class="fa fa-times"></i> Cancel</button>
							<button type="submit" class="btn assign-modal-btn submit" id="assigned_supplier" name="assigned_supplier"><i class="fa fa-check"></i> Assign Supplier</button>
						</div>
					</form>
				</div>
			</div>
		</div>


		<script>
			$(document).ready(function(){
				$('table').dataTable( {
					order: [[0, 'desc']]
				});
			});

			$(document).on("click",".supplier_tagged",function() {
				var data=$(this).attr('data-value'); 
				$("#requisition_id").val(data);
				$("#assign_requisition_code").text($(this).attr('data-code'));
				$("#supplier_id").val('');
			});
		</script>


		<?php
		if(isset($_POST['assigned_supplier'])){
			mysqli_query($conn,"START TRANSACTION");

			$supplier_id = isset($_POST['supplier_id']) ? (int)$_POST['supplier_id'] : 0;
			$requisition_id = isset($_POST['requisition_id']) ? (int)$_POST['requisition_id'] : 0;

			$queryUpStatus = "UPDATE paper_requisition SET supp_id = ".$supplier_id." WHERE id = ".$requisition_id;
			$supp_added = ($supplier_id > 0 && $requisition_id > 0) ? mysqli_query($conn,$queryUpStatus) : false;

			if($supp_added){
				mysqli_query($conn,"COMMIT");
				?>
				<script>
					alert("Supplier Successfully Tagged");
					window.open('index.php?page=Requisition/view-requisition','_self');
				</script>
				<?php
			}else{
				mysqli_query($conn,"ROLLBACK");			
				?>
				<script>

					alert_toast("Error",'danger');
				</script>
				<?php
			}
		}
		?>
		<?php
	}else{
		include 'accessDenied.php';
	}
	?>
