<?php include('db_connect.php');

$module_for_active = 20;
if(in_array("20",$_SESSION['login_Permisions']))
{
	?>
	<div class="container-fluid">

		<div class="col-lg-12">
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<div class="card-header">
							<b>Supplier Order </b>

							<span class="float:right"><a class="btn btn-primary nav-add-supplier btn-sm col-sm-2 float-right" href="index.php?page=add-supplier-order" id="new_order">
								<i class="fa fa-plus"></i> New 
							</a></span>

						</div>
						<div class="card-body">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Supp Order No</th>
										<th>Supplier</th>
										<th>Receiving Date</th>
										<th>Total Bill</th>
										<th>Generated by</th>
										<th>Status</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									<?php
									$category = $conn->query("SELECT a.*,b.supp_name,c.name as userName FROM supplier_order as a INNER JOIN suppliers as b on a.supp_id = b.supp_id INNER JOIN users as c on a.user_id = c.id order by a.id DESC");
									while($row=$category->fetch_assoc()):

										$order_deatils = "SELECT count(srd_id) as cou FROM supplier_order_details WHERE sr_id = ".$row['id'];
										$result_order_details = mysqli_query($conn,$order_deatils);
										if(mysqli_num_rows($result_order_details)>0){
											$row_count = mysqli_fetch_array($result_order_details);
											$colspanVal = $row_count['cou'];
										}else{
											$colspanVal = 0;
										}
										?>
										<tr>
											<td class="text-center">ORD-<?php echo $row['id'] ?></td>
											<td class=""><?php echo $row['supp_name'] ?></td>
											<td><?php echo $row['dated'] ?></td>
											<td style="text-align: right"><?php echo number_format($row['total_amount'],2) ?></td>
											<td><?php echo $row['userName'] ?></td>
											<td><?php
											if($row['req_status'] == 0){
												?><span style="color:red"><b>Pending</b></span><?php
											}elseif($row['req_status'] == 1){
												?><span style="color:blue"><b>Partial Received</b></span><?php
											}else{
												?>
												<span style="color: green"><b>Received</b></span>
												<?php
											}
											?></td>
											<td>
												<span class="float:right">
													<a class="btn btn-success btn-sm " href="index.php?page=view-supplier-order-details&id=<?php echo $row['id'] ?>" id="edit_order">
														<i class="fa fa-eye"></i> 
													</a>
												</span>
											</td>

										</tr>

									<?php endwhile; ?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- Table Panel -->
			</div>
		</div>	


		<script>

			$(document).ready(function(){
				$('table').dataTable();
			});
		</script>

		<?php
	}else{
		include 'accessDenied.php';
	}
	?>