<?php
include '../db_connect.php';
$payment_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
$order = $conn->query("SELECT a.*, b.supp_name AS suppName, u.name AS receiverName FROM supplier_payment AS a INNER JOIN suppliers AS b ON a.supplier_id = b.supp_id LEFT JOIN users AS u ON a.user_id = u.id WHERE a.pay_id = {$payment_id} LIMIT 1");
if(!$order || !$order->num_rows){ echo '<div class="supplier-payment-empty">Payment record not found.</div>'; return; }
$payment = $order->fetch_assoc();
function supplier_payment_value($value, $fallback = '-'){$value = trim((string)$value);return htmlspecialchars($value !== '' ? $value : $fallback, ENT_QUOTES, 'UTF-8');}
$pay_mode = ((int)$payment['payment_mode'] === 1) ? 'Cash' : 'Cheque';
$pay_code = 'SPAY-'.str_pad((int)$payment['pay_id'], 6, '0', STR_PAD_LEFT);
$payment_date_text = date('d M Y', strtotime($payment['payment_date']));
$cheque_date_text = !empty($payment['cheque_date']) && $payment['cheque_date'] !== '0000-00-00' ? date('d M Y', strtotime($payment['cheque_date'])) : '-';
?>
<style>
	.supplier-payment-receipt{font-family:Arial,sans-serif;color:#303033;background:#fff}.supplier-payment-receipt *{box-sizing:border-box}.supplier-receipt-header{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:4px 0 16px;border-bottom:2px solid #f36b21}.supplier-receipt-title{display:flex;align-items:center;gap:12px}.supplier-receipt-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:11px;color:#fff;background:linear-gradient(145deg,#f36b21,#df5812)}.supplier-receipt-title h2{margin:0;font-size:19px;font-weight:650}.supplier-receipt-title p{margin:4px 0 0;font-size:11px;color:#85868c}.supplier-payment-status{padding:7px 11px;border:1px solid #bde4cf;border-radius:20px;font-size:10px;font-weight:700;color:#267b53;background:#edf9f2}
	.supplier-payment-overview{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:16px 0}.supplier-payment-card{padding:12px 14px;border:1px solid #e5e6e9;border-left:3px solid #f36b21;border-radius:9px;background:#fafafa}.supplier-payment-card span,.supplier-payment-detail label{display:block;margin-bottom:5px;font-size:9px;font-weight:700;letter-spacing:.06em;color:#85868c;text-transform:uppercase}.supplier-payment-card strong{font-size:13px}.supplier-payment-section{margin:18px 0 8px;padding-left:9px;border-left:4px solid #f36b21;font-size:11px;font-weight:700;color:#55565b;text-transform:uppercase}.supplier-payment-details{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));border:1px solid #e5e6e9;border-radius:10px;overflow:hidden}.supplier-payment-detail{min-height:58px;padding:11px 13px;border-bottom:1px solid #eeeeef}.supplier-payment-detail:nth-child(odd){border-right:1px solid #eeeeef}.supplier-payment-detail:nth-last-child(-n+2){border-bottom:0}.supplier-payment-detail div{font-size:12px;font-weight:550}.supplier-payment-total{display:flex;align-items:center;justify-content:space-between;margin-top:16px;padding:15px 17px;border:1px solid #ffd7c1;border-radius:10px;background:#fff6f0}.supplier-payment-total span{font-size:11px;font-weight:700;color:#6f7075;text-transform:uppercase}.supplier-payment-total strong{font-size:22px;color:#e25d18}.supplier-payment-total small{margin-right:5px;font-size:10px;color:#9a6f59}.supplier-payment-meta{display:flex;justify-content:space-between;margin-top:14px;padding-top:12px;border-top:1px solid #ececef;font-size:9px;color:#909196}.supplier-payment-empty{padding:30px;text-align:center;color:#777}
	@media(max-width:600px){.supplier-payment-overview,.supplier-payment-details{grid-template-columns:1fr}.supplier-payment-detail:nth-child(odd){border-right:0}.supplier-payment-detail:nth-last-child(2){border-bottom:1px solid #eee}.supplier-receipt-header{align-items:flex-start;flex-direction:column}}@media print{body{margin:12mm}.supplier-payment-receipt{max-width:900px;margin:auto}.supplier-payment-card,.supplier-payment-total,.supplier-payment-status{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style>
<div class="supplier-payment-receipt">
	<div class="supplier-receipt-header"><div class="supplier-receipt-title"><span class="supplier-receipt-icon"><i class="fa fa-truck"></i></span><div><h2>Supplier Payment Receipt</h2><p>Payment transaction and settlement details</p></div></div><span class="supplier-payment-status">Payment Processed</span></div>
	<div class="supplier-payment-overview"><div class="supplier-payment-card"><span>Payment Number</span><strong><?php echo $pay_code; ?></strong></div><div class="supplier-payment-card"><span>Payment Date</span><strong><?php echo $payment_date_text; ?></strong></div><div class="supplier-payment-card"><span>Supplier</span><strong><?php echo supplier_payment_value($payment['suppName']); ?></strong></div><div class="supplier-payment-card"><span>Payment Method</span><strong><?php echo $pay_mode; ?></strong></div></div>
	<div class="supplier-payment-section">Transaction Details</div>
	<div class="supplier-payment-details"><div class="supplier-payment-detail"><label>Reference</label><div><?php echo supplier_payment_value($payment['reference']); ?></div></div><div class="supplier-payment-detail"><label>Consignee Name</label><div><?php echo supplier_payment_value($payment['consignee_name']); ?></div></div><div class="supplier-payment-detail"><label>Cheque Number</label><div><?php echo supplier_payment_value($payment['cheque_no']); ?></div></div><div class="supplier-payment-detail"><label>Cheque Date</label><div><?php echo $cheque_date_text; ?></div></div><div class="supplier-payment-detail"><label>Processed By</label><div><?php echo supplier_payment_value($payment['receiverName'], 'System User'); ?></div></div><div class="supplier-payment-detail"><label>Payment Mode</label><div><?php echo $pay_mode; ?></div></div></div>
	<div class="supplier-payment-total"><span>Total Amount Paid</span><strong><small>PKR</small><?php echo number_format((float)$payment['amount'],2); ?></strong></div><div class="supplier-payment-meta"><span>Transaction: <?php echo $pay_code; ?></span><span>System generated supplier receipt</span></div>
</div>
